<?php

use Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;

$messengerClasses = array(
	PluginFlashMessenger::NAMESPACE_INFO => 'info',
	PluginFlashMessenger::NAMESPACE_ERROR => 'danger',
	PluginFlashMessenger::NAMESPACE_SUCCESS => 'success',
	PluginFlashMessenger::NAMESPACE_DEFAULT => 'info',
	PluginFlashMessenger::NAMESPACE_WARNING => 'warning'
);
$this->flashMessenger()->setMessageOpenFormat('<div%s>');
$this->flashMessenger()->setMessageCloseString('</div>');
$this->flashMessenger()->setMessageSeparatorString('</div><div%s>');
foreach($messengerClasses as $messengerClass => $cssClass){
	echo $this->flashMessenger()->render($messengerClass, array('alert', 'alert-'.$cssClass, 'alert-dismissible'));
}
