<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZfcAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') 
                                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') 
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
	                ->prependStylesheet($this->basePath() . '/css/lightbox.css')
                    ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

    <!-- Scripts -->
	<?php $this->bower('admin', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php $this->bower('ieLT9', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/bootstrap-lightbox.js'); ?>
  </head>

  <body style="padding-top: 70px;">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('zfcadmin') ?>">ZfcAdmin</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav navbar-nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
