<?php if(!empty($_GET["page"]) && $_GET["page"] == "riot"):
	echo "8e447855-8376-4caf-ab35-5f8f9f951914"; 
	die();
endif; ?>
<?php echo $this->doctype(); ?>
<!-- Website Template by freewebsitetemplates.com -->
<html lang="de">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/iconselect.css')
                    ->prependStylesheet($this->basePath() . '/css/template.css') ?>

    <!-- Scripts -->
	<?php $this->bower('main', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php $this->bower('ieLT9', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>
	<?php echo $this->headScript() ?> 
</head>
<body>
	<div id="background">
		<div id="header">
			<div>
				<div>
					<a href="<?php echo $this->url('home') ?>" class="logo"><img src="img/logo.png" alt=""></a>
					<?php echo $this->navigation('navigation')
									->menu()
									->setMinDepth(0)
									->setMaxDepth(0)
									->setonlyActiveBranch(false)
									->setUlClass('')
									->setPartial('partial/navigation.phtml')
									->render(); ?>
				</div>
			</div>
		</div>
		<div id="body">
			<div>
				<div>
		            <?php echo $this->content; ?>
				</div>
			</div>
		</div>
		<div id="footer">
			<div>
				<ul>
					<li id="facebook"> <!-- Turniergruppe -->
						<a target="_blank" href="https://www.facebook.com/groups/339517166200659/">facebook</a>
					</li>
					<li id="googleplus"> <!-- Communitygruppe -->
						<a target="_blank" href="https://www.facebook.com/groups/439327219510270/">RWTH GG</a>
					</li>
					<li id="bitstars">
						<a target="_blank" href="http://www.bitstars.com">Bitstars</a>
					</li>
					<li id="fachschaft">
						<a target="_blank" href="http://www.fsmpi.rwth-aachen.de">Fachschaft</a>
					</li>					
					
					<!--li id="facebook">
						<a target="_blank" href="https://www.facebook.com/groups/439327219510270/">facebook</a>
					</li -->
					<!-- li id="twitter">
						<a href="http://freewebsitetemplates.com/go/twitter/">twitter</a>
					</li>
					<li id="googleplus" style="height: 73px">
						<a href="http://freewebsitetemplates.com/go/googleplus/">googleplus</a>
					</li -->
				</ul>
				<p>
					League of Legends AK isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.
				</p>
			</div>
		</div>
	</div>
    <?php echo $this->inlineScript() ?>
</body>
</html>