<?php
	$files = scandir('./public/img/featured');
	$featured = array();
	foreach($files as $file){
		if(pathinfo($file, PATHINFO_EXTENSION) == 'png'){
			$featured[] = $this->basePath().'/img/featured/'.$file;
		}
	}
	shuffle($featured);
?>
<script type="text/javascript">
	// Image Swap //
	var img1_is_visible = false;
	var featuredImgs = ["<?= implode('", "', $featured) ?>"];
	function swap(i) {
		var img1 = document.getElementById("img1");
		var img2 = document.getElementById("img2");
		var imgold= img1_is_visible ? img1 : img2;
		var imgnew= img1_is_visible ? img2 : img1;

		imgnew.style.opacity = 1.0;
		imgnew.src = featuredImgs[i];
		imgold.style.opacity = 0.0;
		img1_is_visible = !img1_is_visible;
		setTimeout(function(){swap((i+1) % featuredImgs.length)},5000);
	}
	setTimeout(function(){swap(1)},5000);
</script>
<div class="featured">
	<img id="img1" src="<?= $featured[0] ?>" alt="">
	<img id="img2" src="<?= $featured[0] ?>" alt="">
</div>
<div class="section">
	<div>
            <h3>RWTH University LoL Summer Championship 2015</h3>
            <div>
                <div style="float: right; border: none; padding: 0px 0 10px 10px;">
                    <span style="border-top: 1px solid #22272a;"><a href="<?= $this->url('anmeldung/form'); ?>">Zur Anmeldung</a></span>
                    <span><a href="<?= $this->basePath('documents/ausschreibung_SS15.pdf'); ?>" target="_blank">Ausschreibung</a></span>
                    <span><a href="<?= $this->basePath('documents/regeln.pdf'); ?>" target="_blank">Turnierregeln</a></span>
                </div>
                <p>Es ist mal wieder soweit, die RWTH Gaming Group und der LoL AK der Fachschaft I/1 eröffnen die Anmeldung zum RWTH University LoL Summer Championship 2015!</b>
                <p>Das Turnier richtet sich in erster Linie an Studierende und Angehörige der RWTH und FH Aachen, aber auch Externe, die gerne mitspielen wollen, sind willkommen.</p>
                <br>
                <p>Meldet euch jetzt an!</p>
            </div>
	</div>
	<div>
            <h3>Die Turnier-Orga</h3>
            <div>
                <p> Die RWTH Gaming Group und der LoL AK der Fachschaft I/1 organisieren und leiten das Turnier.
                <p> Wir sind alles Studierende der RWTH und haben das gemeinsame Ziel an der RWTH eine Gaming-Community zu gründen. JederR der/die Interesse daran hat kann gerne bei uns mitarbeiten </p>
            </div>
	</div>
</div>