<div class="section">
	<div>
		<h3>Wer darf Teilnehmen?</h3>
		<div>
			<p>Teilnahmeberechtigt sind alle Studierenden und Angestellten der RWTH und FH Aachen mit einem LoL Account auf Level 20 oder höher. Der Nachweis erfolgt dabei durch Angabe einer gültigen RWTH/FH Mailadresse bei der Anmeldung. </p>
			<p>Pro Team dürfen zusätzlich bis zu zwei externe Spieler dabei sein (genauere Details stehen unter Anmeldung).</p> 
		</div>
	</div>
	<div>
		<h3>Anmeldung</h3>
		<div>
			<p>Anmeldeschluss ist Freitag der 10.10.2014 um 24:00 Uhr.</p>
			<p>Ihr könnt euch einzeln oder in Gruppen von bis zu 5 Spielern anmelden. Oder auch nur als Ersatzspieler.</p>
			<p>Unvollständige Teams werden von uns nach Anmeldeschluss durch Einzelanmeldungen oder andere Teams aufgefüllt.</p> 
			<p>Bei Teamanmeldungen (ab zwei Spielern) dürfen bis zu drei externe Spieler pro Team dabei sein, es muss aber immer mindestens ein Teammitglied der RWTH oder FH angehören. Das heißt bei Teamanmeldungen mit 2 Spielern darf maximal ein Externer dabei sein, bei 3 Spielern maximal 2 Externe und bei Anmeldungen mit 4 oder 5 Spielern dürfen maximal 3 Externe dabei sein.</p>
		</div>
	</div>
	<div>
		<h3>Ablauf</h3>
		<div>
			<p>Nach den ersten drei Matches in der Vorrunde startet die Hauptrunde mit sechs Runden im leicht modifizierten Schweizer System. Die besten 16 Teams nach der Hauptrunde qualifizieren sich für die Playoffs, die dann als K.O. Turnier ausgetragen werden. Alle Matches werden als Best of Three ausgetragen. Das Finale und Halbfinale sind LIVE am 31.01. und 01.02.2015 (Details dazu folgen noch).</p>
		</div>
	</div>

	<div>
		<h3>Ersatzspieler</h3>
		<div>
			<p>Für das Turnier werden Ersatzspieler gebraucht, damit es zu möglichst wenig Spielausfällen kommt. Ein Ersatzspieler ist dazu da einzuspringen, wenn in einem Team ein regulärer Spieler ausfällt. Es kann durchaus vorkommen, dass ein Ersatzspiler zu mehr Spielen kommt, als reguläre Spieler.</p>
			<p>Ein Ersatzspieler darf aber nur dann einspringen wenn der reguläre Spieler gleich stark oder stärker ist.</p>
		</div>
	</div>
	<div>
		<h3>Streaming</h3>
		<div>
			<p>Wir versuchen, die meisten Spiele zu streamen und suchen immer Streamer dafür. Wer Lust hat, meldet sich einfach bei der Turnierleitung.</p>
		</div>
	</div>
	<div>
		<h3>Preise</h3>
		<div>
			<p>Sehr wahrscheinlich wird es auch etwas zu gewinnen geben. Was genau hängt davon ab, ob und wie viele Sponsoren wir bekommen. Im letzten Turnier haben alle Spieler der ersten drei Teams Mystery-Scins erhalten</p>
		</div>
	</div>
	<div>
		<h3>Turnierregeln und weiter Details</h3>
		<div>
			<p>Alle Turnierregeln sowie näher Details zum Turnier stehen in der Turnierausschreibung </p>
		</div>
	</div>
</div>
