<div class="section">
    <div>
        <h3>Turnierregeln und Ausschreibung</h3>
        <div>
            <p>Alle Turnierregeln sowie nähere Details zum Turnier stehen in der <b><a href="<?php echo $this->basePath('documents/ausschreibung_SS15.pdf'); ?>">Ausschreibung</a></b> und in unserem <b><a href="<?php echo $this->basePath('documents/regeln.pdf'); ?>">Turnierregelwerk</a></b>.</p>
            <p>Die folgenden Stichpunkte fassen die wesentlichen Information als Hilfe kurz zusammen. Für den Turnierverlauf gilt aber, was in den o.g. Dokumenten steht, die solltet also alle Teilnehmer lesen.</p>
        </div>
    </div>
    <div>
        <h3>Wer darf Teilnehmen?</h3>
        <div>
            <p>Teilnahmeberechtigt sind nur Universitätsangehörigen (Studenten, Alumnis, Mitarbeiter) der RWTH und FH Aachen.</p>
			<p>Außerdem muss jeder Teilnehmer über TeamSpeak 3 verfügen, um die Ergebnisse zu melden.</p>
			<p>Um einen pünktlichen Start zu gewährleisten müssen alle Spieler spätestens 30 Minuten vor Beginn in TeamSpeak und League of Legends online sein und in beiden Clients den Chatroom RWTHNovember1v1 joinen.</p>
        </div>
    </div>
    <div>
        <h3>Anmeldung</h3>
        <div>
            <p>Anmeldeschluss ist Freitag der 13.11.2015 um 24:00 Uhr.</p>
            <p>Das Turnier wird eins gegen eins gespielt, daher kann man sich nur einzeln anmelden.</p>
        </div>
    </div>
    <div>
        <h3>Ablauf</h3>
        <div>
            <p>Das Turnier wird vollständig am Sonntag, dem 15.11.2015 ab 13 Uhr ausgetragen. Gespielt wird auf der 'Howling Abyss' Karte, eins gegen eins.</p> 
            <p>Ein Spielt gilt als gewonnen, wenn zwei der drei folgenden Ziele erreicht sind:</p>
			<ul>
				<li>100 Minions last hitten</li>
				<li>Mindestens ein Tod des Gegners (Exekutionen zählen aus)</li>
				<li>Ein zerstörter Tower</li>
			</ul>
			<p>Der Turniermodus ist ein K.O.-System mit double elimination</p>
        </div>
    </div>
</div>
