<div class="section">
    <div>
        <h3>Turnierregeln und Ausschreibung</h3>
        <div>
            <p>Alle Turnierregeln sowie nähere Details zum Turnier stehen in der <b><a href="documents/ausschreibung_SS15.pdf">Ausschreibung</a></b> und in unserem <b><a href="documents/regeln.pdf">Turnierregelwerk</a></b>.</p>
            <p>Die folgenden Stichpunkte fassen die wesentlichen Information als Hilfe kurz zusammen. Für den Turnierverlauf gilt aber, was in den o.g. Dokumenten steht, die solltet also alle Teilnehmer lesen.</p>
        </div>
    </div>
    <div>
        <h3>Wer darf Teilnehmen?</h3>
        <div>
            <p>Teilnahmeberechtigt sind alle Universitätsangehörigen (Studenten, Alumnis, Mitarbeiter) der RWTH und FH Aachen, die einen League of Legends Account auf Level 20 oder höher haben.</p>
            <p>Bei Teamanmeldungen dürfen auch externe Spieler dabei sein, Details dazu findet ihr im Abschnitt Anmeldung.</p> 
        </div>
    </div>
    <div>
        <h3>Anmeldung</h3>
        <div>
            <p>Anmeldeschluss ist Freitag der 10.04.2015 um 24:00 Uhr.</p>
            <p>Ihr könnt euch einzeln oder in Gruppen von bis zu 8 Spielern (5 Stammspieler mit bis zu 3 Ersatzspielern) anmelden. Wahlweise könnt ihr euch auch nur als Ersatzspieler für alle Teams anmelden.</p>
            <p>Unvollständige Teams werden von uns nach Anmeldeschluss durch Einzelanmeldungen oder andere Teams aufgefüllt.</p>
            <p>Bei Teamanmeldungen (ab zwei Spielern) dürfen externe Spieler dabei sein, allerdings müssen mindestens 40% der Teammitglieder Universitätsangehörige sein.</p>
        </div>
    </div>
    <div>
        <h3>Ablauf</h3>
        <div>
            <p>Das Turnier gliedert sich in eine drei Runden lange Einspielphase, eine sechs Runden lange Hauptphase im leicht modifizierten Schweizer System. Die besten 8 Teams der Hauptphase qualifizieren sich für die Playoffs, die im K.o.-System ausgetragen werden.</p> 
            <p>Alle Matches werden online als Best-of-Three gespielt.</p>
        </div>
    </div>
    <div>
        <h3>Ersatzspieler</h3>
        <div>
            <p>In diesem Turnier kann jedes Teams eigene Ersatzspieler anmelden. Weiterhin ist bei Einzelanmeldungen auch die Anmeldung als globaler Ersatzspieler möglich, der für alle Teams einspringen kann, wenn ein regulärer Spieler ausfällt.</p>
            <p>Globale Ersatzspieler können nur Spieler ersetzen, die das gleiche oder ein höheres Ranking besitzen.</p>
        </div>
    </div>
    <div>
        <h3>Streaming</h3>
        <div>
            <p>Wir versuchen, die meisten Spiele zu streamen und suchen immer Streamer dafür. Wer Lust hat, meldet sich einfach bei der Turnierleitung.</p>
        </div>
    </div>
    <div>
        <h3>Preise</h3>
        <div>
            <p>In diesem Semester haben wir erstmals die offiziellen Community-Turnierpreise von Riot zu vergeben. Außerdem sind wir natürlich weiterhin bemüht, Sponsoren für weitere Preise zu finden.</p>
            <p>Im letzten Turnier haben alle Spieler der ersten drei Teams Mystery-Skins erhalten</p>
        </div>
    </div>
</div>
