<div class="media">
	<div class="article">
		<h3>Kontakt</h3>
		<ul>
			<li>
				<p>Die Turnier-Orga ist per Mail unter <br><a href="mailto:leagueoflegends@lists.fsmpi.rwth-aachen.de">leagueoflegends@lists.fsmpi.rwth-aachen.de</a><br>zu erreichen. Wenn Du Fragen oder Anregungen hast, schreib uns einfach eine Mail.</p>
			</li>
			<li>
				<p><b>Die Turnier-Orga:</b></p>
				<p>Aleksandr Grinspun<br>Beschwörername: xelax90<br><a href="https://www.facebook.com/alex.grinspun" target="_blank">Aleks@Facebook</a></p>
				<p>Eiko Kerinnis<br>Beschwörername: Fei D Fluorite<br><a href="https://www.facebook.com/eiko.kerinnis" target="_blank">Eiko@Facebook</a></p>
				<p>Florian Großkreuz<br>Beschwörername: PandaHouse<br><a href="https://www.facebook.com/grosskreutz" target="_blank">Florian@Facebook</a></p>
				<!-- p>Fachschaft I/1 Mathe/Physik/Informatik<br>Karmanstra&szlig;e 7, 3. Etage<br>52062 Aachen</p>
				<p>Oder auf der Hörn:<br>Ahornstraße 55, Raum 2014/2015<br>52074 Aachen</p -->
			</li>
		</ul>
	</div>
	<div class="article">
		<h3>Impressum</h3>
		<ul>
			<li>
				<p>Fachschaft Mathematik Physik Informatik<br>
					Templergraben 55</br>
					52056 Aachen</p>
			</li>
			<li>
				
			</li>
		</ul>
	</div>
</div>
