<div class="media">
    <div class="article">
        <h3>Kontakt</h3>
        <ul>
            <li>
                <p>Die Turnier-Orga ist per Mail unter <br><a href="mailto:leagueoflegends@lists.fsmpi.rwth-aachen.de">leagueoflegends@lists.fsmpi.rwth-aachen.de</a><br>zu erreichen. Wenn Du Fragen oder Anregungen hast, schreib uns einfach eine Mail.</p>
            </li>
            <li>
                <p><b>Die Turnier-Orga:</b></p>
                <p>Florian Großkreutz<br>Beschwörername: PandaHouse<br><a href="https://www.facebook.com/Grosskreutz" target="_blank">Florian@Facebook</a></p>
                <p>Markus Brieden<br>Beschwörername: Fetza<br><a href="https://www.facebook.com/profile.php?id=100010564360830&fref=ts" target="_blank">Markus@Facebook</a></p>
                <p>Dennis Matz<br>Beschwörername: Barroi<br><a href="https://www.facebook.com/dennis.matz.54" target="_blank">DennisM@Facebook</a></p>
            </li>
        </ul>
    </div>
    <div class="article">
        <h3>Impressum</h3>
        <ul>
            <li>
                <p>Fachschaft Mathematik Physik Informatik<br>
                    Templergraben 55</br>
                    52056 Aachen</p>
            </li>
        </ul>
    </div>
</div>