<?php
$form = $this->form;
$form->prepare();
$routeParams = array('group_id' => $this->group->getId());
if(!empty($this->preset)){
	$routeParams['preset'] = $this->preset;
}
$form->setAttribute('action', $this->url('zfcadmin/runden/create', $routeParams));
$form->setAttribute('method', 'post');

$presetForm = $this->presetForm;
$presetForm->prepare();
$presetForm->setAttribute('action', $this->url('zfcadmin/runden/setpreset', array('group_id' => $this->group->getId())));
$presetForm->setAttribute('method', 'post');
?>

<h1><?php echo $this->translate('Neue Runde auslosen') ?></h1>

<h2>Preset auswählen (optional) </h2>
<?php echo $this->form()->openTag($presetForm) ?>
    <dl class="zend_form">
        <?php foreach ($presetForm as $element): ?>
            <?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
            <?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
            <?php if ($element->getLabel() != null && !$isButton): ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
            <?php if ($isButton): ?>
                <dd><?php echo $this->formButton($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
                <dd><?php echo $this->formSelect($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
                <dd><?php echo $this->formMultiCheckbox($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                <dd><?php echo $this->formTextarea($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($isCheckbox): ?>
                <dd><?php echo $this->formCheckbox($element) ?></dd>
            <?php else: ?>
                <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
            <?php endif ?>
        <?php endforeach ?>
    </dl>
<?php echo $this->form()->closeTag() ?>

<h2>Daten eintragen</h2>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php foreach ($form as $element): ?>
            <?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
            <?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
            <?php if ($element->getLabel() != null && !$isButton): ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
            <?php if ($isButton): ?>
                <dd><?php echo $this->formButton($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
                <dd><?php echo $this->formSelect($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
                <dd><?php echo $this->formMultiCheckbox($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                <dd><?php echo $this->formTextarea($element) . $this->formElementErrors($element) ?></dd>
            <?php elseif ($isCheckbox): ?>
                <dd><?php echo $this->formCheckbox($element) ?></dd>
            <?php else: ?>
                <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
            <?php endif ?>
        <?php endforeach ?>
    </dl>
<?php echo $this->form()->closeTag();