<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/myteams/edit', array('team_id' => $form->getObject()->getId())));
$form->setAttribute('method', 'post');
?>

<script type="text/javascript">
	jQuery(function($){
		$(function(){
			$('input[type=checkbox],input[type=radio]').each(function(){
				if($(this).data('switch')){
					$(this).bootstrapSwitch();
				}
			});
			
		});
	}(jQuery));
</script>


<h1><?php echo $this->translate('Team bearbeiten') ?></h1>

<?php echo $this->twbForm($form);
