<?php
$form = $this->ergebnisForm;
$form->prepare();
$form->setAttribute('action', $this->formAction);
$form->setAttribute('method', 'post');
?>

<?php
$errors = '';
foreach($form as $element){
	$errors .= $this->formElementErrors($element);
}
?>

<?php if(!empty($errors)) : ?>
	<div class="reportresult error"><?= $errors ?></div>
<?php endif;?>

<?php echo $this->form()->openTag($form) ?>
<?php foreach ($form as $element): ?>
	<?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
	<?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
	<?php if ($element->getLabel() != null && !$isButton): ?>
		<?php echo $this->formLabel($element) ?>
	<?php endif ?>
	<?php if ($isButton): ?>
		<?php echo $this->formButton($element) ?>
	<?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
		<?php echo $this->formTextarea($element) ?>
	<?php elseif ($element instanceof Zend\Form\Element\Select): ?>
		<?php echo $this->formSelect($element) ?>
	<?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
		<?php echo $this->formMultiCheckbox($element) ?>
	<?php elseif ($element instanceof Zend\Form\Element\File): ?>
		<?php echo $this->formFile($element) ?>
	<?php elseif ($isCheckbox): ?>
		<?php echo $this->formCheckbox($element) ?>
	<?php else: ?>
		<?php echo $this->formInput($element) ?>
	<?php endif ?>
<?php endforeach ?>
<?php echo $this->form()->closeTag() ?>
