<?php $player = $this->player; ?>
<div class="player" style="margin: 0  0 10px 0; background-image: url('<?= $this->fsmpiLoLDDragon()->profileIcon($player->getAnmeldung()->getSummonerdata()->getProfileIconId()) ?>'); <?= $this->addStyles ?: '' ?>">
	<?php if(($player->getIsCaptain() && $this->showCaptainContact) || $this->showAllContacts) : ?>
	<div class="player_summonername <?= $player->getIsCaptain() && $this->showCaptain ? 'captain' : '' ?>"><?= $player->getAnmeldung()->getName() ?></div>
	<div class="<?= $this->showEmailRight ? 'player_rankedWins' : 'player_level' ?>"><?= $player->getAnmeldung()->getEmail() ?></div>
	<?php endif; ?>
	<div class="player_summonername <?= $player->getIsCaptain() && $this->showCaptain ? 'captain' : '' ?>"><?= $player->getAnmeldung()->getSummonerName() ?></div>
	
	<?php if($this->showWins) : ?>
	<div class="player_rankedWins">Ranked: <?= $player->getAnmeldung()->getSummonerdata()->getRankedWins() ?> Siege</div>
	<?php endif; ?>
	
	<div class="player_level">Level <?= $player->getAnmeldung()->getSummonerdata()->getLevel() ?>, <?= $player->getAnmeldung()->getSummonerdata()->getTier() ?></div>
	
	<?php if($this->showWins) : ?>
	<div class="player_normalWins">Normal: <?= $player->getAnmeldung()->getSummonerdata()->getNormalWins() ?> Siege</div>
	<?php endif; ?>
	
	<?php if($player->getIsCaptain() && $this->showCaptain) : ?>
	<div class="player_subborder"></div>
	<?php endif; ?>
</div>
