<?php 
/** @var $player \FSMPILoL\Entity\Player */
$player = $this->player; 

$iconId = 0;
$rankedWins = 0;
$level = 0;
$tier = 'Unranked';
$normalWins = 0;
if(!empty($player->getAnmeldung()->getSummonerdata())){
	$iconId = $player->getAnmeldung()->getSummonerdata()->getProfileIconId();
	$rankedWins = $player->getAnmeldung()->getSummonerdata()->getRankedWins();
	$level = $player->getAnmeldung()->getSummonerdata()->getLevel();
	$normalWins = $player->getAnmeldung()->getSummonerdata()->getNormalWins();
	$tier = $player->getAnmeldung()->getSummonerdata()->getTier();
}
?>
<div class="player" style="margin: 0  0 10px 0; background-image: url('<?= $this->fsmpiLoLDDragon()->profileIcon($iconId) ?>'); <?= $this->addStyles ?: '' ?>">
	<?php if(($player->getIsCaptain() && $this->showCaptainContact) || $this->showAllContacts) : ?>
	<div class="player_summonername <?= $player->getIsCaptain() && $this->showCaptain ? 'captain' : '' ?>"><?= $player->getAnmeldung()->getName() ?></div>
	<div class="<?= $this->showEmailRight ? 'player_rankedWins' : 'player_level' ?>">
		<?php if($this->emailWithLink): ?>
		<a href="mailto:<?= rawurlencode($player->getAnmeldung()->getName() . " <".$player->getAnmeldung()->getEmail().">") ?>">
		<?php endif;?>
			<?= $player->getAnmeldung()->getEmail() ?>
		<?php if($this->emailWithLink): ?>
		</a>
		<?php endif;?>
	</div>
	<?php endif; ?>
	<div class="player_summonername <?= $player->getIsCaptain() && $this->showCaptain ? 'captain' : '' ?>"><?= $player->getAnmeldung()->getSummonerName() ?></div>
	
	<?php if($this->showWins) : ?>
	<div class="player_rankedWins">Ranked: <?= $rankedWins ?> Siege</div>
	<?php endif; ?>
	
	<div class="player_level">Level <?= $level ?>, <?= $tier ?></div>
	
	<?php if($this->showWins) : ?>
	<div class="player_normalWins">Normal: <?= $normalWins ?> Siege</div>
	<?php endif; ?>
	
	<?php if($player->getIsCaptain() && $this->showCaptain) : ?>
	<div class="player_subborder"></div>
	<?php endif; ?>
	<div style="clear: both"></div>
</div>
