<?php 
	$team = $this->team;
	$match = $this->match;
	
	$teamSide = '';
	if($match != null){
		if($match->getTeamHome() == $team){
			$teamSide = ' home ';
		} elseif($match->getTeamHome() == $team){
			$teamSide = ' guest ';
		}
	}
	
	if($team != null) :
		$js = '';
		$playersId = '';
		if($match){
			$containerIds = array();
			if($match->getTeamHome()){
				$containerIds[] = "#players_".$match->getRound()->getNumber()."_".$match->getTeamHome()->getId();
			}
			if($match->getTeamGuest()){
				$containerIds[] = "#players_".$match->getRound()->getNumber()."_".$match->getTeamGuest()->getId();
			}
			
			$js = "var elms = $('".implode(", ", $containerIds)."'); if(elms.css('display') == 'block'){elms.css('display', 'none')} else {elms.css('display', 'block')}";
			$js = ' onclick="'.$js.'" ';
			
			$playersId = 'players_'.$match->getRound()->getNumber().'_'.$team->getId();
			$playersId = ' id="'.$playersId.'" ';
		} else {
			$containerIds = array();
			$containerIds[] = "#players_".$team->getId();
			$js = "var elms = $('".implode(", ", $containerIds)."'); if(elms.css('display') == 'block'){elms.css('display', 'none')} else {elms.css('display', 'block')}";
			$js = ' onclick="'.$js.'" ';
			
			$playersId = 'players_'.$team->getId();
			$playersId = ' id="'.$playersId.'" ';
		}
		
	?>
	<div class="team <?= $teamSide ?>" style="background-image: url('<?= $this->basePath() ?>/img/teamicons/<?= $team->getIcon() ?>')">
		<div class="teamname" <?= $js ?>><?= $team->getName() ?> (<?= $team->getData()->getPoints() ?>) <?= $this->showScore ? '('.$team->getScore().')' : '' ?> <?= $this->showFarberwartung ? $team->getData()->getFarberwartung() : '' ?></div>
		<div class="players" <?= $playersId ?>>
	<?php
		foreach($team->getPlayers() as $player):
			echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array('player' => $player) + $this->playerOptions);
		endforeach;
	?>
		</div>
	</div>
<?php else : ?>
	<div class="team <?= $teamSide ?>">
		<div class="teamname">Spielfrei</div>
	</div>
<?php endif; ?>
