<?php
	define('DEBUG', false);
	$tournament = $this->tournament;
?>

<div class="anmeldung ergebnisse">
	<div class="content">
		<ul class="results">
			<?php
			$groupCount = count($tournament->getGroups());
			foreach($tournament->getGroups() as $group) :
			?>
			<li>
				<?php if($groupCount > 1) : ?>
				<div class="header">
					<b>Gruppe <?= $group->getNumber() ?></b>
				</div>
				<?php endif; ?> 
				
				<div class="article">
					<div class="standings">
						<?php
							$position = 0;
							$teams = $group->getTeams()->toArray();
							usort($teams, array('FSMPILoL\Entity\Team', 'comparePoints'));
							foreach($teams as $team) :
								if(!$team->hasCaptain())
									continue;
							?>
							<div class="standing <?= $position == 0 ? "first" : "" ?>">
								<div class="position"><?= $position + 1 ?></div>
								<div class="buchholz">Buchh <br> <?= $team->getData()->getBuchholz() ?></div>
								<div class="score"><?= $team->getData()->getPoints() ?></div>
								
								<?php
									echo $this->partial('fsmpi-lo-l/tournament/partial/team.phtml', array(
										'team' => $team,
										'showFarberwartung' => false,
										'playerOptions' => array(
											'addStyles' => '',
											'showCaptain' => false,
											'showCaptainContact' => false,
											'showAllContacts' => false,
											'showWins' => true
										),
									));
								?>
							</div>
							<?php
								$position++;
							endforeach;
						?>
					</div>
				</div>
			</li>
			<?php
			endforeach;
			?>
		</ul>
	</div>
</div>
