<?php
$team = $this->team;
?>
<div class="anmeldung teams">
	<div class="content">
		<ul>
			<?php echo $this->partial('fsmpi-lo-l/tournament/partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url('myteam'))) ?>
			<li style="width: 920px; margin-right: 0px;">
				<div class="header">
					<b><img style="width: 52px; vertical-align: middle; margin-right: 10px;" src="<?= $this->basePath() ?>/img/teamIcons/<?= $team->getIcon() ?>"><?php echo $team->getName() ?></b>
				</div>
				<div class="article">
					<div class="players">
						<?php 
							foreach($team->getPlayers() as $player){
								echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
									'player' => $player,
									'addStyles' => '',
									'showCaptain' => true,
									'showCaptainContact' => true,
									'showAllContacts' => $this->fsmpiLoLTournamentPermission()->isAllowed('viewContacts', $team),
									'showWins' => true,
									'showEmailRight' => true
								));
							}; 
						?>
					</div>
				</div>
			</li>
			<li style="width: 920px; margin-right: 0px;">
				<div class="header">
					<b>Ersatzspieler</b>
				</div>
				<div class="article">
					<div class="players">
						<?php foreach($this->tournament->getSubs() as $player) : 
							echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
								'player' => $player,
								'addStyles' => 'margin: 0  0 10px 0; ',
								'showCaptain' => false,
								'showCaptainContact' => false,
								'showAllContacts' => $this->fsmpiLoLTournamentPermission()->isAllowed('viewSubContacts', $team),
								'showWins' => true,
								'showEmailRight' => true
							));
						endforeach; ?>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
