<?php
$tournament = $this->tournament;
?>
		<div class="anmeldung ergebnisse">
			<div class="content">
				<ul class="paarungen">
					<?php echo $this->partial('fsmpi-lo-l/tournament/partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url('meldung'))) ?>
					<?php
					$groupCount = count($tournament->getGroups());
					foreach($tournament->getGroups() as $group) :
						foreach($group->getRounds() as $round) : 
							if($round->getIsHidden() && !$this->isAllowed('tournament', 'round/viewHidden')){
								continue;
							}
						?>
						<li>
							<div class="header" <?= $round->getIsHidden() ? 'style="border-color: red;"' : '' ?>>
								<b>Runde <?= $round->getNumber() ?> <?= $round->getIsHidden() ? "(Nicht freigegeben)" : "" ?></b>
							</div>

							<div class="article">
								<div class="matches">
									<?php
										$position = 0;
										foreach($round->getMatches() as $match) :
											$pointsHome = "";
											$pointsGuest = "";
											foreach($match->getGames() as $game){
												if($game->getPointsBlue() !== null || $game->getPointsPurple() !== null){
													$pointsHome  += $match->getTeamHome()  == $game->getTeamBlue() ? $game->getPointsBlue() : $game->getPointsPurple();
													$pointsGuest += $match->getTeamGuest() == $game->getTeamBlue() ? $game->getPointsBlue() : $game->getPointsPurple();
												}
											}
											
											$result = "";
											$result .= $match->getPointsHome() === null ? $pointsHome : $match->getPointsHome();
											$result .= " - ";
											$result .= $match->getPointsGuest() === null ? $pointsGuest : $match->getPointsGuest();
											//if($result != " - ")
											//	$result = '<a href="gameinfo.html?gameid='.$game->gameID.'">'.$result.'</a>';
											
											echo $this->partial('fsmpi-lo-l/tournament/partial/paarung.phtml', array(
												'match' => $match,
												'position' => $position,
												'result' => $result,
												'showGamedate' => true,
												'teamOptions' => array(
													'showFarberwartung' => false,
													'playerOptions' => array(
														'addStyles' => '',
														'showCaptain' => true,
														'showCaptainContact' => $this->fsmpiLoLTournamentPermission()->isAllowed('viewCaptain', $match->getTeamHome()) || $this->fsmpiLoLTournamentPermission()->isAllowed('viewCaptain', $match->getTeamGuest()),
														'showAllContacts' => false,
														'showWins' => false
													)
												)
											));
											$position++;
										endforeach;
									?>
								</div>
							</div>
						</li>
						<?php
						endforeach;
					endforeach;
					?>
				</ul>
			</div>
		</div>
