<?php
use FSMPILoL\Entity\User;
use FSMPILoL\Form\ErgebnismeldungForm;
use FSMPILoL\Form\ZeitmeldungForm;

define('DEBUG', false);

$tournament = $this->tournament;
$identity = $this->zfcUserIdentity();
if($identity)
	define('ADMIN', $identity->getRole() <= User::ROLE_ADMIN);
else
	define('ADMIN', false);

		if(!$identity || $identity->getRole() <= User::ROLE_MODERATOR || true) :
		?>
		<div class="anmeldung ergebnisse">
			<div class="content">
				<ul class="paarungen">
					<?php echo $this->partial('fsmpi-lo-l/tournament/partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url('meldung'))) ?>
					<?php
					$groupCount = count($tournament->getGroups());
					foreach($tournament->getGroups() as $group) :
						//$rounds = $group->getRounds()->toArray();
						//usort($rounds, function($a, $b){return $b->getNumber() - $a->getNumber();});
						foreach($group->getRounds() as $round) : 
						?>
						<li>
							<div class="header">
								<b>Runde <?= $round->getNumber() ?></b>
							</div>

							<div class="article">
								<div class="matches">
									<?php
										$position = 0;
										foreach($round->getMatches() as $match) :
											$pointsHome = "";
											$pointsGuest = "";
											$g = 0;
											foreach($match->getGames() as $game){
												if($game->getPointsBlue() !== null && $game->getPointsPurple() !== null){
													$pointsHome  += $g % 2 == 0 ? $game->getPointsBlue()   : $game->getPointsPurple();
													$pointsGuest += $g % 2 == 0 ? $game->getPointsPurple() : $game->getPointsBlue();
												}
												$g++;
											}
											
											$result = "";
											$result .= $match->getPointsHome() === null ? $pointsHome : $match->getPointsHome();
											$result .= " - ";
											$result .= $match->getPointsGuest() === null ? $pointsGuest : $match->getPointsGuest();
											//if($result != " - ")
											//	$result = '<a href="gameinfo.html?gameid='.$game->gameID.'">'.$result.'</a>';
											
											echo $this->partial('fsmpi-lo-l/tournament/partial/paarung.phtml', array(
												'match' => $match,
												'position' => $position,
												'result' => $result,
												'showGamedate' => true,
												'teamOptions' => array(
													'showFarberwartung' => false,
													'playerOptions' => array(
														'addStyles' => '',
														'showCaptain' => true,
														'showCaptainContact' => false,
														'showAllContacts' => false,
														'showWins' => false
													)
												)
											));
											$position++;
										endforeach;
									?>
								</div>
							</div>
						</li>
						<?php
						endforeach;
					endforeach;
					?>
				</ul>
			</div>
		</div>
<?php endif;