<div class="anmeldung teams">
	<div class="content">
		<ul>
			<?php echo $this->partial('fsmpi-lo-l/tournament/partial/loginForm.phtml', array('loginForm' => $this->loginForm, 'formAction' => $this->url('meldung'))) ?>
			<?php
				$tournament = $this->tournament;
				foreach($tournament->getGroups() as $group) : 
					$c = 0;
					foreach($group->getTeams() as $team):
						if($team->getIsBlocked()){
							continue;
						}
						$showContacts = $this->fsmpiLoLTournamentPermission()->isAllowed('viewContacts', $team);
				?>
				<li style="margin-right: <?= (1 - $c % 2) * 20 ?>px; <?= $showContacts ? '' : "width: 920px; margin-right: 0px;" ?> ">
					<div class="header" <?= $this->isAllowed('tournament', 'debug/moderator') && $team->hasCaptain() ? 'style="border-color: green;"' : '' ?>>
						<b><img style="width: 52px; vertical-align: middle; margin-right: 10px;" src="<?= $this->basePath() ?>/img/teamIcons/<?= $team->getIcon() ?>"><?php echo $team->getName() ?></b>
						<?= $this->isAllowed('tournament', 'debug/moderator') ? '<div style="clear: left">'.$team->getAnsprechpartner().'</div>' : ''; ?>
					</div>
					<div class="article">
						<div class="players">
							<?php $players = $team->getPlayers()->toArray(); ?>
							<?php usort($players, function($a, $b){return !$a->getIsCaptain() && !$b->getIsCaptain() ? 0 : ($a->getIsCaptain() ? -1 : 1); }) ?>
							<?php 
								foreach($players as $player){
									echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
										'player' => $player,
										'addStyles' => $showContacts ? '' : "min-height: 57px; padding-top: 0px;",
										'showCaptain' => true,
										'showCaptainContact' => $this->fsmpiLoLTournamentPermission()->isAllowed('viewCaptain', $team),
										'showAllContacts' => $showContacts,
										'showWins' => true,
										'showEmailRight' => true
									));
								}; 
							?>
						</div>
					</div>
				</li>
				<?php
					$c++;
					endforeach;
				endforeach;
			?>
			<li style="width: 920px; margin-right: 0px;">
				<div class="header">
					<b>Ersatzspieler</b>
				</div>
				<div class="article">
					<div class="players">
						<?php foreach($tournament->getSubs() as $player) : 
							echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
								'player' => $player,
								'addStyles' => 'margin: 0  0 10px 0; ',
								'showCaptain' => false,
								'showCaptainContact' => false,
								'showAllContacts' => $this->fsmpiLoLTournamentPermission()->isAllowed('viewSubContacts', $tournament),
								'showWins' => true,
								'showEmailRight' => true
							));
						endforeach; ?>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
