<?php
define('DEBUG', false);
define('ADMIN', false);
define('DDRAGON_VERSION', '4.19.2');
// TODO Login
/*
$idAnmeldung = null;
if(!empty($_GET['id']))
	$idAnmeldung = LoLDB::escape($_GET['id']);
*/
?>
<div class="anmeldung teams">
	<div class="content">
		<ul>
			<li style="width: 100%; float: none;">
				<div class="header">
					<b>Login</b>
				</div>
				<div class="article">
					<form action="teams.html" method="GET">
						<input type="text" placeholder="Code" name="id" style="float: left;">
						<input type="submit" value="Login" style="height: 21px; margin: 2px 0;">
						<?php if(DEBUG) : ?>
						<input type="hidden" name="test" value="">
						<?php endif;?>
					</form>
				</div>
			</li>
			<?php
				$tournament = $this->tournament;
				foreach($tournament->getGroups() as $group) : 
					$c = 0;
					foreach($group->getTeams() as $team):
						if($team->getIsBlocked())
							continue;
						// If ID is set
						$isIDAnmeldungTeam = false;
						/* TODO
						if(!empty($idAnmeldung)){
							foreach($team->players as $player){
								if($player->urlid == $idAnmeldung){
									$isIDAnmeldungTeam = true;
								}
							}
						}
						if(substr($team->teamname, 0, 4) == "Sub_")
							continue;
						*/
						$hasCaptain = false;
						foreach($team->getPlayers() as $player){
							if($player->getIsCaptain())
								$hasCaptain = true;
						}
				?>
				<li style="margin-right: <?= (1 - $c % 2) * 20 ?>px; <?= empty($idAnmeldung) || ADMIN ? '' : "width: 920px; margin-right: 0px;" ?> ">
					<div class="header" <?= DEBUG && $hasCaptain ? 'style="border-color: green;"' : '' ?>>
						<b><img style="width: 52px; vertical-align: middle; margin-right: 10px;" src="<?= $this->basePath() ?>/img/summoner_icons/<?= $team->getIcon() ?>"><?php echo $team->getName() ?></b>
						<?= ADMIN ? '<div style="clear: left">'.$team->getAnsprechpartner().'</div>' : ''; ?>
					</div>
					<div class="article">
						<div class="players">
							<?php $players = $team->getPlayers()->toArray(); ?>
							<?php usort($players, function($a, $b){return !$a->getIsCaptain() && !$b->getIsCaptain() ? 0 : ($a->getIsCaptain() ? -1 : 1); }) ?>
							<?php 
								foreach($players as $player){
									echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
										'player' => $player,
										'addStyles' => empty($idAnmeldung) ? '' : "min-height: 57px; padding-top: 0px;",
										'showCaptain' => true,
										'showCaptainContact' => false,
										'showAllContacts' => false,
										'showWins' => true
									));
								}; 
							?>
						</div>
					</div>
				</li>
				<?php
					$c++;
					endforeach;
				endforeach;
			?>
			<li style="width: 920px; margin-right: 0px;">
				<div class="header">
					<b>Ersatzspieler</b>
				</div>
				<div class="article">
					<div class="players">
						<?php foreach($tournament->getSubs() as $player) : 
							echo $this->partial('fsmpi-lo-l/tournament/partial/player.phtml', array(
								'player' => $player,
								'addStyles' => 'margin: 0  0 10px 0; ',
								'showCaptain' => true,
								'showCaptainContact' => false,
								'showAllContacts' => false,
								'showWins' => true
							));
						endforeach; ?>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
